### PR TITLE
fix typing.List[YamlConfig] support

### PR DESCRIPTION
**Pull request by hirachan**
I found MyDataClass.load() cannot convert dictionary into MySubDataClass when it is in the list like following.

```
@dataclass
class MyDataClass:
    sub_vals: typing.List[MySubDataClass]
```

I fixed the list of dictionary can be converted in to a list of MySubDataClass.

### CODE REVIEW

**Comment by kzmssk** [comment]
Thank you for PR.
Let me check the diff and merge if your commit is ok ASAP.

**Comment by hirachan** [comment]
I also added support for dict like this.
```
@dataclass
class MyDataClass:
    sub_vals: typing.Dict[str, MySubDataClass]
```

**Comment by hirachan** [comment]
Hmm, there are still other patterns..
`sub_vals: typing.Dict[str, typing.List[MySubDataClass]]`
`sub_vals: typing.List[typing.Dict[str, MySubDataClass]]`
`sub_vals: typing.Dict[str, typing.Dict[str, MySubDataClass]]`
....

**Comment by hirachan** [comment]
Sorry for many postings.
I made it to convert recursively.
I think this is final.

**Comment by kzmssk** [comment]
@hirachan  I checked the PR. The code looks good and the tests passed with Python 3.7.4 in my environment. Thank you for your commits!

**Pull request merged**
